### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by jedireza** [spacekit/spacekit#35]
I'm seeting this at the relay:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
```

**Comment by jedireza** [comment]
Closing because obviously not helpful 😉
