### ISSUE TITLE
Error to investigate

### ISSUE THREAD

**Issue by jedireza** [spacekit/spacekit#36]
```
[2016-04-23T03:04:23.357Z] ERROR: SpaceKit/14435 on raspberrypi: error terminating TLS connection (module=TlsTerminatingSocket, err.code=ECONNRESET)
    Error: socket hang up
        at SecurePair.error (_tls_legacy.js:818:23)
        at EncryptedStream.CryptoStream._done (_tls_legacy.js:469:22)
        at EncryptedStream.read [as _read] (_tls_legacy.js:300:12)
        at EncryptedStream.Readable.read (_stream_readable.js:328:10)
        at CleartextStream.onCryptoStreamFinish (_tls_legacy.js:111:47)
        at CleartextStream.g (events.js:260:16)
        at emitNone (events.js:72:20)
        at CleartextStream.emit (events.js:166:7)
        at finishMaybe (_stream_writable.js:468:14)
        at endWritable (_stream_writable.js:478:3)
        at CleartextStream.Writable.end (_stream_writable.js:443:5)
        at CleartextStream.CryptoStream.end (_tls_legacy.js:406:31)
        at Socket.onend (_stream_readable.js:490:10)
        at Socket.g (events.js:260:16)
        at emitNone (events.js:72:20)
        at Socket.emit (events.js:166:7)
```

**Comment by jedireza** [comment]
Closing because obviously not helpful 😉
