### ISSUE TITLE
Dynamic DNS race condition?

### ISSUE THREAD

**Issue by mcav** [spacekit/spacekit#45]
```
~/moz/spacekit $ spacekit laptop 8000:9000                                                                                                                                                                                2:47PM
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned. 
 - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735421 [invalid]
   DNS problem: NXDOMAIN looking up A for laptop.mcav.spacekit.io
 - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735422 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735423 [pending]
    at handleErr (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/n{"name":"SpaceKit","hostname":"mcav.local","pid":37604,"module":"TlsCertificateGenerator","level":50,"err":{"message":"The CA was unable to validate the file you provisioned. \n - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735421 [invalid]\n   DNS problem: NXDOMAIN looking up A for laptop.mcav.spacekit.io\n - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735422 [pending]\n - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735423 [pending]","name":"Error","stack":"Error: The CA was unable to validate the file you provisioned. \n - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735421 [invalid]\n   DNS problem: NXDOMAIN looking up A for laptop.mcav.spacekit.io\n - https://acme-v01.api.letsencrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735422 [pending]\n - https://acme-v01.api.letseode_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ncrypt.org/acme/challenge/KGv84snVRRgYAKMQINhIZcdvMl6EnAZdgIcFTV-4tNI/89735423 [pending]\n    at handleErr (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:372:17)\n    at ensureValidation (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:245:16)\n    at Request._callback (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/letiny-core/lib/get-certificate.js:227:13)\n    at Request.self.callback (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/request/request.js:200:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/request/request.js:1067:10)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/Users/marcus/.nvm/versions/node/v6.1.0/lib/node_modules/spacekit/node_modules/request/request.js:988:12)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:926:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"},"msg":"Failed to obtain TLS certificate!","time":"2016-05-19T12:47:53.145Z","v":0}
^C

```

**Comment by mcav** [comment]
Closed by #48
