### ISSUE TITLE
Exception thrown while generating SSL certificate

### ISSUE THREAD

**Issue by Sija** [spacekit/spacekit#67]
I got following exception while generating SSL certificate.
Seems like it's happening only for the first time. Next run successfully finishes.

```
Traffic routed through SpaceKit is encrypted end-to-end.
We are now generating a new TLS certificate with LetsEncrypt.
This can take up to one minute, and it only needs to be done once.

Please wait...

*************************************************************
Failure: We were unable to obtain a TLS certificate for you:
 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/letsencrypt/lib/core.js:274:31
    at tryCatcher (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/sija/.nvm/versions/node/v6.9.1/lib/node_modules/spacekit/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
*************************************************************
This is fatal and unexpected. Please submit a bug report. :(
(node:54188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received undefined
```

**Comment by jedireza** [comment]
Thanks for opening an issue. I ran into a similar error recently too. I'll begin looking into this further.
